# Generated by Django 6.1.1 on 2026-09-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("RESPONDER", "Responder"),
                    ("VIEWER", "Viewer"),
                ],
                default="RESPONDER",
                max_length=20,
            ),
        ),
    ]
