# Generated by Django 6.1.1 on 2026-09-28 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_role"),
        ("monitoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=3)),
                ("timeout_ms", models.PositiveIntegerField(default=5000)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="monitoring.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("DATABASE", "Database"),
                            ("API_TIMEOUT", "API Timeout"),
                            ("AUTH_SECURITY", "Auth / Security"),
                            ("SERVER_CRASH", "Server Crash"),
                            ("PERFORMANCE", "Performance"),
                        ],
                        default="SERVER_CRASH",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("P1", "P1 - Critical"),
                            ("P2", "P2 - High"),
                            ("P3", "P3 - Moderate"),
                            ("P4", "P4 - Low"),
                        ],
                        default="P3",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIGGERED", "Triggered"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="TRIGGERED",
                        max_length=20,
                    ),
                ),
                (
                    "raw_logs",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Stack trace or raw failure output",
                    ),
                ),
                (
                    "ai_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured root-cause diagnosis from AI triage",
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="accounts.organization",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="monitoring.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TRIGGERED", "Triggered"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("COMMENT", "Comment"),
                            ("AI_TRIAGE", "AI Triage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
