# Generated by Django 6.1.1 on 2026-09-27 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "target_url",
                    models.URLField(
                        help_text="Live URL to health check, e.g. https://httpbin.org/status/200"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("DEGRADED", "Degraded"),
                            ("MAJOR_OUTAGE", "Major Outage"),
                        ],
                        default="OPERATIONAL",
                        max_length=20,
                    ),
                ),
                ("check_interval_sec", models.PositiveIntegerField(default=60)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthCheckLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("is_success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("checked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_logs",
                        to="monitoring.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
    ]
